### PR TITLE
Fix build on kernel 6.8+ (WMI notify API, remove callback, jiffies; auto-detected)

### PR DESCRIPTION
**Pull request by RimachOfficial**
## Summary

Fixes the DKMS build failure on kernel 6.8 (e.g. Ubuntu 6.8.0-136):

```
hp-wmi.c:1486:63: error: passing argument 2 of 'wmi_install_notify_handler' from incompatible pointer type
hp-wmi.c:2567:28: error: initialization of 'int (*)(struct platform_device *)' from incompatible pointer type 'void (*)(struct platform_device *)'
hp-wmi.c:2585:34: error: implicit declaration of function 'secs_to_jiffies'
```

The project supports kernels before 6.20, so the new APIs are **auto-detected at build time** (same pattern as the existing `omen_pp_compat.h` / `OMEN_PP_API_*` logic) rather than assuming one kernel generation.

## Changes

**`hp-wmi.c`**
1. **`wmi_notify_handler` signature** — kernel 6.11+ changed the handler to `void (*)(u32 value, void *context)` (see `include/linux/acpi.h`). The new path fetches the event payload with `wmi_get_event_data()` and `kfree()`s the ACPI buffer on every path; the legacy `union acpi_object *` handler is kept for older kernels behind `#ifdef OMEN_WMI_API_NEW`.
2. **`platform_driver.remove`** — pre-transition kernels require `int (*)(struct platform_device *)`; post-transition kernels use `void`. Dual-gated behind `#ifdef OMEN_REMOVE_RETURNS_INT`.
3. **`secs_to_jiffies()`** — removed in newer kernels; replaced with `msecs_to_jiffies(KEEP_ALIVE_DELAY_SECS * 1000)` (constant-folded) which works on all kernels.

**`Makefile`** — the `omen_pp_compat.h` rule now also defines `OMEN_WMI_API_NEW` when `wmi_get_event_data` is present in the kernel headers, and `OMEN_REMOVE_RETURNS_INT` when `platform_device.h` still declares `int (*remove)(struct platform_device *)`.

## Testing

- Build-tested against Ubuntu kernel 6.8.0-136-generic headers: `omen_pp_compat.h` generated with all three defines (`OMEN_PP_API_HANDLER`, `OMEN_WMI_API_NEW`, `OMEN_REMOVE_RETURNS_INT`), `hp-wmi.ko` compiles with no errors.
- Installed via `install_driver.sh` DKMS flow on 6.8.0-136 (module signed, loaded successfully, persists across reboots).
- The feature-detection mirrors the project's existing `OMEN_PP_API_*` approach, so older kernels (6.1-6.10/6.13/6.18) continue to use the legacy handler/remove signatures.

### CODE REVIEW

**Comment by arfelious** [comment]
Thanks for the contribution. I needed to rebase as there were many conflicts after I merged a PR regarding project structure and updated the hp-wmi we use which changed many things. I changed portions of code to use LINUX_VERSION_CODE instead of find and grep, use KERNEL_BUILD in Makefile, change return type based on kernel version for a function and a few other things.
